server:
  port: 8501
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.45.239.63:3306/db_spzx?characterEncoding=utf-8&useSSL=true
    username: root
    password: 200056
  data:
    redis:
      host: 119.45.239.63
      port: 6379
      password: 1234
mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml
spzx:
  minio:
    endpointUrl: http://119.45.239.63:9001
    accessKey: admin
    secreKey: admin123456
    bucketName: spzx-bucker